ff4fe-post-randomizer --edit-vchest sylph-yang-5treasures-clockwise-1="Fire Arrows" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-5treasures-clockwise-2="Ice Arrows" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-5treasures-clockwise-3="Lit Arrows" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-5treasures-clockwise-4="Ether1" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-5treasures-clockwise-5="Cure2" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-nearsave-left="Cabin" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-nearsave-right="1000" $roma
ff4fe-post-randomizer --edit-vchest sylph-1="Charm Arrows" $roma
ff4fe-post-randomizer --edit-vchest sylph-2="Bestiary" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-elvenbow="Elven Bow" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section21-bottomright="Cure3" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section21-bottomleft="Ether1" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section21-topright="Cure2" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section21-middleleft="Heal" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section21-topleft="Heal" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section20-topleft="Heal" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section20-topright="Cure2" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section20-bottomleft="2000" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section20-bottomright="3000" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-toadladybox="Mute Dagger" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section1-left="Cure2" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section1-top="Charm Rod" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section1-bottom="Heal" $roma
ff4fe-post-randomizer --edit-vchest sylph-yang-longhall="Elixir" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section3-topleft="FireBomb" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section3-topmiddle="Blizzard" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section3-topright="Lit-Bolt" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section3-bottomleft="Full Moon" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section3-bottommiddle="Avenger" $roma
ff4fe-post-randomizer --edit-vchest sylph-other-section3-bottomright="Medusa Arrows" $roma
ff4fe-post-randomizer --edit-vchest sylph-house-top="Poison Claw" $roma
ff4fe-post-randomizer --edit-vchest sylph-house-bottom="Cat Claw" $roma
